import type { ITranslationsProps } from "~/types/type.ts";

export const defaultTranslations: ITranslationsProps = {
  bold: "Bold",
  italic: "Italic",
  underline: "Underline",
  strike: "Strike",
  header1: "Header 1",
  header2: "Header 2",
  header3: "Header 3",
  unorderedList: "Bullet List",
  orderedList: "Ordered List",
  checklist: "Checklist",
  alignLeft: "Align left",
  center: "Align Center",
  alignRight: "Align right",
  undo: "Undo",
  redo: "Redo",
  table: "Table",
  tableRemove: "Remove Table",
  addColumnBefore: "Add Column Before",
  addColumnAfter: "Add Column After",
  removeColumn: "Remove Column",
  addRowBefore: "Add Row Before",
  addRowAfter: "Add Row After",
  removeRow: "Remove Row",
  TableMerge: "Merge Table",
  textStyle: "Text Style",
};
